#!/usr/bin/env python3
"""Turn the legacy Google Sheets export into a seed migration.

Usage:
    python3 scripts/csv_to_seed.py "Menu - Sayfa1.csv" > supabase/migrations/20261003000003_seed_menu.sql

Columns expected: (blank), Name, Description, Price, Category, Photo URL
Parenthetical notes like "(400 kcal)", "(Süt ürünleri içerir.Alerjendir.)" and
"(çölyak hastaları için uygun değildir.)" are lifted out of the description
into the calories / allergens / not_celiac_safe columns.
"""
import csv
import re
import sys

CELIAC_NOTE = (
    "Taş değirmende çekilmiş karabuğdayla hazırlanır. Çapraz bulaşma riski nedeniyle "
    "çölyak hastaları için uygun değildir."
)
CATEGORY_SUBTITLES = {
    "Glutensiz Yemekler": CELIAC_NOTE,
    "Glutensiz Ürünler": CELIAC_NOTE,
    "Çorbalar": "Çorba çeşitleri günlük olarak değişmektedir.",
}

PAREN = re.compile(r"\(([^()]*)\)")
KCAL = re.compile(r"(\d+)\s*k[a-z]al", re.IGNORECASE)


def sql(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + value.replace("'", "''") + "'"


def tidy(text):
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s+([,.;])", r"\1", text)
    text = re.sub(r"([,;])(?=\S)", r"\1 ", text)
    text = re.sub(r"\.(?=[A-Za-zÇĞİÖŞÜçğıöşü])", ". ", text)
    text = re.sub(r"(?<=[a-zçğıöşü])\.+(?=\d)", ". ", text)
    text = re.sub(r",(\s*,)+", ",", text)
    text = text.replace(";", ",")
    text = re.sub(r",(\s*,)+", ",", text)
    return text.strip(" ,.;")


def sentence(text):
    text = tidy(text)
    return text[:1].upper() + text[1:] if text else text


def parse_description(raw):
    raw = (raw or "").replace("\n", " ").strip()
    calories = None
    allergens = []
    celiac = False

    def handle(match):
        nonlocal calories, celiac
        inner = match.group(1).strip()
        low = inner.lower()
        kcal = KCAL.search(inner)
        if kcal and len(inner) < 20:
            calories = int(kcal.group(1))
            return " "
        if "çölyak" in low:
            celiac = True
            return " "
        if "içerir" in low or "alerjen" in low:
            note = re.sub(r"\.?\s*alerjendir\.?", "", inner, flags=re.IGNORECASE)
            allergens.append(sentence(note))
            return " "
        return match.group(0)

    text = PAREN.sub(handle, raw)

    # Notes written without parentheses, or with a dangling "(".
    text = re.sub(r"\(\s*$", "", text)
    tail = re.search(
        r"((?:süt|yumurta|balık|sert|kabuklu|bal)\b[^.()]*içerir\.?\s*alerjendir\.?)\s*$",
        text,
        flags=re.IGNORECASE,
    )
    if tail:
        note = re.sub(r"\.?\s*alerjendir\.?", "", tail.group(1), flags=re.IGNORECASE)
        allergens.append(sentence(note))
        text = re.sub(r"\(\s*$", "", text[: tail.start()].rstrip())
    if "çölyak" in text.lower():
        celiac = True
        text = re.sub(r"\(?çölyak[^)]*\)?\.?", " ", text, flags=re.IGNORECASE)
    kcal = KCAL.search(text)
    if kcal and calories is None:
        calories = int(kcal.group(1))
        text = text.replace(kcal.group(0), " ")

    description = sentence(text) or None
    if description and not description.endswith((".", ")", "!")):
        description += "."
    return description, calories, "; ".join(a for a in allergens if a) or None, celiac


def clean_url(url):
    url = (url or "").strip()
    if not url:
        return None
    return url.replace("??", "?")


def main(path):
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.reader(fh))

    header, rows = rows[0], rows[1:]
    idx = {name.strip(): i for i, name in enumerate(header)}

    categories = []
    items = []
    for row in rows:
        if len(row) < len(header):
            continue
        name = row[idx["Name"]].strip()
        category = row[idx["Category"]].strip()
        if not name or not category:
            continue
        if category not in categories:
            categories.append(category)
        description, calories, allergens, celiac = parse_description(row[idx["Description"]])
        items.append(
            {
                "category": category,
                "name": re.sub(r"\s+", " ", name),
                "description": description,
                "price": float(row[idx["Price"]].strip() or 0),
                "calories": calories,
                "allergens": allergens,
                "celiac": celiac,
                "photo_url": clean_url(row[idx["Photo URL"]]),
            }
        )

    out = [
        "-- Seed: menu imported from the legacy Google Sheet (Menu - Sayfa1.csv).",
        "-- Generated by scripts/csv_to_seed.py. Safe to re-run: it skips when items exist.",
        "",
        "insert into public.site_settings (id, price_note, prices_updated_on, reviews_url)",
        "values (1, 'Fiyatlara tüm vergiler dahildir', '2025-03-29',",
        "        'https://www.google.com/search?q=Medipoint+Wellness+Cafe+%26+Restaurant+Yorumlar')",
        "on conflict (id) do nothing;",
        "",
        "do $seed$",
        "begin",
        "  if exists (select 1 from public.menu_items) then",
        "    raise notice 'menu_items already populated, skipping seed';",
        "    return;",
        "  end if;",
        "",
        "  insert into public.categories (name, subtitle, sort_order) values",
    ]
    out.append(
        ",\n".join(
            f"    ({sql(c)}, {sql(CATEGORY_SUBTITLES.get(c))}, {(i + 1) * 10})"
            for i, c in enumerate(categories)
        )
        + "\n  on conflict (name) do nothing;"
    )
    out.append("")
    out.append(
        "  insert into public.menu_items\n"
        "    (category_id, name, description, price, calories, allergens, not_celiac_safe, photo_url, sort_order)\n"
        "  select c.id, v.name, v.description, v.price, v.calories, v.allergens, v.celiac, v.photo_url, v.sort_order\n"
        "  from (values"
    )
    counters = {}
    values = []
    for item in items:
        counters[item["category"]] = counters.get(item["category"], 0) + 10
        price = item["price"]
        price_sql = str(int(price)) if price.is_integer() else str(price)
        values.append(
            "    ("
            + ", ".join(
                [
                    sql(item["category"]),
                    sql(item["name"]),
                    sql(item["description"]) + "::text",
                    price_sql + "::numeric",
                    sql(item["calories"]) + "::integer",
                    sql(item["allergens"]) + "::text",
                    sql(item["celiac"]),
                    sql(item["photo_url"]) + "::text",
                    str(counters[item["category"]]),
                ]
            )
            + ")"
        )
    out.append(",\n".join(values))
    out.append(
        "  ) as v(category, name, description, price, calories, allergens, celiac, photo_url, sort_order)\n"
        "  join public.categories c on c.name = v.category;"
    )
    out += ["end", "$seed$;", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
